# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offerings', models.ManyToManyField(blank=True, help_text='List of offerings available for this platform', to='coe_requests.Offering')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.TextField(default='{}', help_text='JSON configuration of the form for a particular platform/offering combination. Should contain a key "hide_fields" with a given list of fields to hide.')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coe_requests.Offering')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coe_requests.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coe_requests.Offering')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coe_requests.Platform')),
            ],
        ),
    ]
