# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformoffering',
            name='configuration',
        ),
        migrations.AddField(
            model_name='platformoffering',
            name='hide_fields',
            field=models.CharField(blank=True, default='', help_text='List of fields to hide for this combination.', max_length=200),
        ),
        migrations.AlterField(
            model_name='platform',
            name='offerings',
            field=models.ManyToManyField(blank=True, help_text='List of offerings to show for this platform', to='coe_requests.Offering'),
        ),
    ]
