# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe_requests', '0002_auto_20161005_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platformoffering',
            unique_together=set([('platform', 'offering')]),
        ),
    ]
